theme = "colibri"

[keys.normal]
C-m = ["jump_view_right", ":buffer-close!",
 ":vsplit-new", ":insert-output ack --group -o ' TODO *.*| FIXME *.*| XXX *.*'",
 "collapse_selection", "goto_file_start", "jump_view_left"]
C-w = ":bc!"

[editor]
true-color = true
line-number = "relative"
mouse = true
shell = ["zsh", "-c"]
cursorline = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = false
