# theme = "colibri"
theme = "kanagawa"

[keys.normal]
C-s = ":w"
C-t = [":sh ack --group -o ' TODO *.*| FIXME *.*| XXX *.*'"]
C-w = ":bc!"
C-q = ":q"
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
esc = ["collapse_selection", "keep_primary_selection"]

[editor]
true-color = true
mouse = true
shell = ["zsh", "-c"]
cursorline = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = false
